---
- name: restart splunk
  service: 
    name: splunk 
    state: restarted
  become: true

- name: systemctl daemon-reload
  systemd: 
    daemon_reload: yes
  become: true

- name: Restart ssh
  service: 
    name: sshd
    state: restarted